# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lcMI8qsPkd9sol6zT2bKTfQJSEvF5Vf
"""

pip install openai

import os
import openai

openai.api_key = 'sk-3OC9AX5PDageMzNBhLkMgUAIMRU4R60yZuk0hIrc'

start_sequence = "\ncode: "
restart_sequence = "\n\ndescription :"
desp = input()
preset = """description:  a red button that says stop
code:  <button style={{color:  'white', backgroundColor: 'red' }}>Stop</button>


description: a button that looks like a watermelon
code: <button style={{color: 'white',borderRadius:'50%', backgroundColor: 'pink', padding: 10, width: 100, height: 100}}> Watermelon</button>


description:a header with text Hello world and have a description of 'Nothing much to do' and have a tag called 'Google' which redirect to google.com and a button named 'watch videos' redirecting to Youtube.
code: 
<div className='App'>
    <h1> Hello World</h1>
    <div Style={{backgroundColor:'red',fontFamily:'Arial'}}>
        <h2> Nothing Much to do </h2>
    </div>
    <a href='https://www.google.com/%27%3E'> Google</a>
    <button> <a href='https://www.youtube.com/%27%3E'> Watch Videos</a></button>
</div>


description:a button for every colour of rainbow
code: 
<div>
    <button style={{backgroundColor:'Red'}}>Red</button>
    <button style={{backgroundColor:'Orange'}}>Orange</button>
    <button style={{backgroundColor:'Yellow'}}>Yellow</button>
    <button style={{backgroundColor:'Green'}}>Green</button>
    <button style={{backgroundColor:'Blue'}}>Blue</button>
    <button style={{backgroundColor:'Indigo'}}>Indigo</button>
    <button style={{backgroundColor:'Violet'}}>Violet</button>
</div>


description : a sign in form page which contain username and password block and submit button with forgot password redirecting link. 
code:
<form>
    <h3>Sign In</h3>
    <div className="form-group">
        <label>Email address</label>
        <input type="email" className="form-control" placeholder="Enter email" />
    </div>
    <div className="form-group">
        <label>Password</label>
        <input type="password" className="form-control" placeholder="Enter password" />
    </div>
    <div className="form-group">
        <div className="custom-control custom-checkbox">
            <input type="checkbox" className="custom-control-input" id="customCheck1" />
            <label className="custom-control-label" htmlFor="customCheck1">Remember me</label>
        </div>
    </div>
    <button type="submit" className="btn btn-primary btn-block">Submit</button>
    <p className="forgot-password text-right">
        Forgot <a href="#">password?</a>
    </p>
</form>


description: a sign up page which contains  firstname,lastname,email address and password block with sign up button with already registered redirecting link.
code:
<form>
    <h3>Sign Up</h3>
    <div className="form-group">
        <label>First name</label>
        <input type="text" className="form-control" placeholder="First name" />
    </div>
    <div className="form-group">
        <label>Last name</label>
        <input type="text" className="form-control" placeholder="Last name" />
    </div>
    <div className="form-group">
        <label>Email address</label>
        <input type="email" className="form-control" placeholder="Enter email" />
    </div>
    <div className="form-group">
        <label>Password</label>
        <input type="password" className="form-control" placeholder="Enter password" />
    </div>
    <button type="submit" className="btn btn-primary btn-block">Sign Up</button>
    <p className="forgot-password text-right">
        Already registered <a href="#">sign in?</a>
    </p>
</form>


description: """+desp+ "\n\n"

response = openai.Completion.create(
  engine="davinci",
  prompt=preset,
  temperature=0.7,
  max_tokens=803,
  top_p=1,
  stop=["\n\n"]
)

print(response.choices[0]['text'])